<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9gqrfR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9gqrfR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF9gqrfR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF9gqrfR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF9gqrfR\App_KernelDevDebugContainer([
    'container.build_hash' => 'F9gqrfR',
    'container.build_id' => '270c32a7',
    'container.build_time' => 1659354045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9gqrfR');
